version: "2"

services:
  nginx:
    image: nginx:latest
    container_name: the-project-nginx
    restart: always
    environment:
      - VIRTUAL_HOST=www.the-project.eddiebarraco.fr,the-project.eddiebarraco.fr
      - LETSENCRYPT_HOST=www.the-project.eddiebarraco.fr,the-project.eddiebarraco.fr
      - LETSENCRYPT_EMAIL=eddiebarraco@live.fr
      - PHP_CONTAINER_NAME=the-project-php
      - SYMFONY_ENTRYPOINT=app.php
    volumes_from:
      - php
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: the-project/php:7.1-fpm
    container_name: the-project-php
    restart: always
    build:
      context: docker/build/php7.1
    volumes:
      - ./:/var/www/html
      - ~/.docker/ReedWade/TheProject/composer:/root/.composer

networks:

  default:
    external:
      name: public
