---
version: '3'

services:
  web:
    image: nginx:latest
    deploy:
      labels:
        traefik.http.frontend.rule: "Host:the-project.eddiebarraco.fr"
        traefik.http.frontend.entryPoints: "http"
        traefik.http.frontend.redirect.entryPoint: "https"
        traefik.http.port: 80
        traefik.https.frontend.rule: "Host:the-project.eddiebarraco.fr"
        traefik.https.frontend.entryPoints: "https"
        traefik.https.port: 443
        traefik.docker.network: web-proxy
    environment:
      - PHP_CONTAINER_NAME=the-project-php
      - SYMFONY_ENTRYPOINT=app.php
    networks:
      web-proxy: ~
      app: ~
    volumes:
      - web-conf:/etc/nginx/conf.d
      - ./:/var/www/html
  php:
    image: docker.misterbanal.net/reedwade/the-project-php:php7.1
    build:
      context: docker/build/php7.1
    volumes:
      - ./:/var/www/html
      - composer-data:/root/.composer
    networks:
      app: ~

volumes:
  web-conf: ~
  composer-data: ~

networks:
  app: ~
  web-proxy:
    external: true
