---
version: '3'

services:
  web:
    image: nginx:latest
    deploy:
      labels:
        traefik.frontend.rule: "Host:the-project.eddiebarraco.fr"
        traefik.frontend.entryPoints: "https"
        traefik.frontend.headers.SSLRedirect: "true"
        traefik.docker.network: traefik_reverse-proxy
        traefik.port: 80
    environment:
      - PHP_CONTAINER_NAME=the-project-php
      - SYMFONY_ENTRYPOINT=app.php
    networks:
      traefik_reverse-proxy: ~
      app: ~
    volumes:
      - web-conf:/etc/nginx/conf.d
      - ./:/var/www/html
  php:
    image: docker.misterbanal.net/reedwade/the-project-php:php7.1
    build:
      context: docker/build/php7.1
    volumes:
      - ./:/var/www/html
      - ~/.docker/ReedWade/TheProject/composer:/root/.composer
    networks:
      app: ~

volumes:
  web-conf: ~

networks:
  app: ~
  traefik_reverse-proxy:
    external: true
